In [8]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\aura\anaconda3\lib\site-packages (9.6.0)

In [9]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\aura\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\aura\anaconda3\lib\site-packages (from openpyxl) (1.1.0)

In [11]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="",
    port="3307"
)

cursor = conn.cursor()

# buat database
cursor.execute("CREATE DATABASE IF NOT EXISTS dbkampus")

# pilih database
cursor.execute("USE dbkampus")

# baca file SQL
with open("dbkampus.sql", "r") as file:
    sql_script = file.read()

# eksekusi
for statement in sql_script.split(";"):
    if statement.strip():
        cursor.execute(statement)

conn.commit()
print("Import berhasil!")

Import berhasil!

In [14]:
import pandas as pd

In [16]:
# Ambil data dari SQL

query = "SELECT * FROM peserta_kelas"
df_mysql = pd.read_sql(query, conn)

print("Data dari MySQL: ")
display(df_mysql.head())

Data dari MySQL:

C:\Users\Aura\AppData\Local\Temp\ipykernel_12340\786973240.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_mysql = pd.read_sql(query, conn)

   id         nim                      nama  angkatan prodi kode_kelas
0   1  0110221344                YUDIANSYAH      2021    TI  DM20252-P
1   2  0110224003  MUHAMMAD BINTANG GUNAWAN      2024    TI  DM20252-P
2   3  0110224004  MUHAMMAD SHOFIYYURROHMAN      2024    TI  DM20252-P
3   4  0110224009              ZAINAB AZNUR      2024    TI  DM20252-P
4   5  0110224012             ARYA NURYAWAN      2024    TI  DM20252-P

In [18]:
df_mysql.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          96 non-null     int64
 1   nim         96 non-null     object
 2   nama        96 non-null     object
 3   angkatan    96 non-null     int64
 4   prodi       96 non-null     object
 5   kode_kelas  96 non-null     object
dtypes: int64(2), object(4)
memory usage: 4.6+ KB

In [20]:
df_mysql.describe()

              id     angkatan
count  96.000000    96.000000
mean   48.500000  2023.968750
std    27.856777     0.306186
min     1.000000  2021.000000
25%    24.750000  2024.000000
50%    48.500000  2024.000000
75%    72.250000  2024.000000
max    96.000000  2024.000000

In [22]:
# Ambil data dari Excel

df_excel = pd.read_excel("DM-252-A-Quiz 3 Data Understanding Kelas Senin Pagi-grades.xlsx")

print("Data dari Excel: ")
display(df_excel.head())

Data dari Excel:

,Last name,First name,Username,ID number,Email address,Mobile phone,State,Started on,Completed,Time taken,...,Q. 6 /6.67,Q. 7 /6.67,Q. 8 /6.67,Q. 9 /6.67,Q. 10 /6.67,Q. 11 /6.67,Q. 12 /6.67,Q. 13 /6.67,Q. 14 /6.67,Q. 15 /6.67
0,Farhan Apriliansyah,Muhamad,110224069.0,110224069.0,0110224069@student.nurulfikri.ac.id,NaN,Finished,13 April 2026 8:17 AM,13 April 2026 8:22 AM,5 mins 54 secs,...,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67
1,Farrelia,Keyla,110224228.0,110224228.0,0110224228@student.nurulfikri.ac.id,NaN,Finished,13 April 2026 8:20 AM,13 April 2026 8:29 AM,9 mins 32 secs,...,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67
2,Febriyanti,Intan,110224028.0,110224028.0,0110224028@student.nurulfikri.ac.id,NaN,Finished,13 April 2026 8:20 AM,13 April 2026 8:30 AM,9 mins 29 secs,...,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67
3,Al Razzak,Rafa,110224155.0,110224155.0,0110224155@student.nurulfikri.ac.id,NaN,Finished,13 April 2026 8:20 AM,13 April 2026 8:27 AM,7 mins 3 secs,...,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67
4,Zahrodiniah,Silvia,110224019.0,110224019.0,0110224019@student.nurulfikri.ac.id,NaN,Finished,13 April 2026 8:20 AM,13 April 2026 8:30 AM,10 mins,...,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67

In [26]:
df_excel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 26 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Last name      46 non-null     object
 1   First name     45 non-null     object
 2   Username       45 non-null     float64
 3   ID number      45 non-null     float64
 4   Email address  45 non-null     object
 5   Mobile phone   0 non-null      float64
 6   State          45 non-null     object
 7   Started on     45 non-null     object
 8   Completed      45 non-null     object
 9   Time taken     45 non-null     object
 10  Grade/100.00   46 non-null     float64
 11  Q. 1 /6.67     46 non-null     float64
 12  Q. 2 /6.67     46 non-null     float64
 13  Q. 3 /6.67     46 non-null     float64
 14  Q. 4 /6.67     46 non-null     float64
 15  Q. 5 /6.67     46 non-null     object
 16  Q. 6 /6.67     46 non-null     object
 17  Q. 7 /6.67     46 non-null     float64
 18  Q. 8 /6.67     46 non-null     float64
 19  Q. 9 /6.67     46 non-null     float64
 20  Q. 10 /6.67    46 non-null     object
 21  Q. 11 /6.67    46 non-null     float64
 22  Q. 12 /6.67    46 non-null     float64
 23  Q. 13 /6.67    46 non-null     object
 24  Q. 14 /6.67    46 non-null     float64
 25  Q. 15 /6.67    46 non-null     float64
dtypes: float64(15), object(11)
memory usage: 9.5+ KB

In [28]:
df_excel.describe()

,Username,ID number,Mobile phone,Grade/100.00,Q. 1 /6.67,Q. 2 /6.67,Q. 3 /6.67,Q. 4 /6.67,Q. 7 /6.67,Q. 8 /6.67,Q. 9 /6.67,Q. 11 /6.67,Q. 12 /6.67,Q. 14 /6.67,Q. 15 /6.67
count,4.500000e+01,4.500000e+01,0.0,46.000000,46.000000,46.000000,46.000000,46.000000,46.000000,46.000000,46.000000,46.000000,46.000000,46.000000,46.000000
mean,1.102241e+08,1.102241e+08,NaN,89.628913,6.373478,5.780652,6.225217,6.076957,6.076957,6.225217,6.076957,6.076957,6.225217,5.780652,5.484130
std,7.154223e+01,7.154223e+01,NaN,10.380445,1.374556,2.267364,1.663791,1.898171,1.898171,1.663791,1.898171,1.898171,1.663791,2.267364,2.550112
min,1.102240e+08,1.102240e+08,NaN,66.670000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.102240e+08,1.102240e+08,NaN,81.667500,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000
50%,1.102241e+08,1.102241e+08,NaN,93.330000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000
75%,1.102242e+08,1.102242e+08,NaN,100.000000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000
max,1.102242e+08,1.102242e+08,NaN,100.000000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000

In [24]:
df_excel + df_excel[['Last name', 'First name', 'ID number', 'Grade/100.00']]

,Completed,Email address,First name,Grade/100.00,ID number,Last name,Mobile phone,Q. 1 /6.67,Q. 10 /6.67,Q. 11 /6.67,...,Q. 4 /6.67,Q. 5 /6.67,Q. 6 /6.67,Q. 7 /6.67,Q. 8 /6.67,Q. 9 /6.67,Started on,State,Time taken,Username
0,NaN,NaN,MuhamadMuhamad,200.00,220448138.0,Farhan ApriliansyahFarhan Apriliansyah,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,KeylaKeyla,200.00,220448456.0,FarreliaFarrelia,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,IntanIntan,200.00,220448056.0,FebriyantiFebriyanti,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,RafaRafa,200.00,220448310.0,Al RazzakAl Razzak,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,SilviaSilvia,200.00,220448038.0,ZahrodiniahZahrodiniah,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,MuhamadMuhamad,200.00,220448224.0,FadilFadil,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,FathiyaturohmahFathiyaturohmah,200.00,220448120.0,FathiyaturohmahFathiyaturohmah,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,ElsiElsi,200.00,220448052.0,NovitasariNovitasari,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,RevaniRevani,200.00,220448222.0,RevaniRevani,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,MuhamadMuhamad,200.00,220448066.0,RojaliRojali,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,AisyaAisya,200.00,220448106.0,Az ZahraAz Zahra,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,RaffaRaffa,200.00,220448162.0,Yuda PratamaYuda Pratama,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,AliaAlia,200.00,220448190.0,MaisyaraMaisyara,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,AyuAyu,200.00,220448232.0,Della AstutiDella Astuti,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,SilvaSilva,186.66,220448042.0,Nurzanatul DahmalenaNurzanatul Dahmalena,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,MutiaMutia,186.66,220448262.0,Rahma AmaliyahRahma Amaliyah,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,LindaLinda,186.66,220448086.0,Agistina HandaniAgistina Handani,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,AmayaAmaya,186.66,220448204.0,EshiaEshia,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,AdindaAdinda,186.66,220448104.0,Angesti ChandraAngesti Chandra,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,AdeliaAdelia,186.66,220448226.0,JulianiJuliani,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,FahreziFahrezi,186.66,220448342.0,NoviansyahNoviansyah,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,SalsabilaSalsabila,186.66,220448062.0,SalsabilaSalsabila,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,FitriFitri,186.66,220448192.0,Aura RamadhaniAura Ramadhani,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,LiraLira,186.66,220448390.0,LiskaLiska,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,LestariLestari,186.66,220448402.0,LestariLestari,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,AanAan,186.66,220448028.0,AdriyanaAdriyana,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,FebiFebi,186.66,220448480.0,FebrianiFebriani,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,MuhammadMuhammad,186.66,220448428.0,Ibnu FajarIbnu Fajar,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,OryzaOryza,173.34,220448060.0,Ayunda PutriAyunda Putri,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,TiaraTiara,173.34,220448160.0,Safitri HandayaniSafitri Handayani,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,SyaifulSyaiful,173.34,220448168.0,IlhamIlham,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,FirtiansyahFirtiansyah,173.34,220448348.0,Okta ResamaOkta Resama,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,MaulidyaMaulidya,173.34,220448132.0,Syifa AszahraSyifa Aszahra,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,MeishaMeisha,160.00,220448360.0,Bongi TelumaBongi Teluma,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,SafiraSafira,160.00,220448178.0,Nur AzkiaNur Azkia,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,SulthanSulthan,160.00,220448468.0,Nabil Al HakimNabil Al Hakim,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,AryaArya,160.00,220448024.0,NuryawanNuryawan,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,AuroraAurora,160.00,220448114.0,Zalfa HartonoZalfa Hartono,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,ArdhikaArdhika,146.66,220448412.0,Adfiansyah SetianaAdfiansyah Setiana,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,ZainabZainab,146.66,220448018.0,AznurAznur,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,SyahrulSyahrul,146.66,220448170.0,Giga WahyudiGiga Wahyudi,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,MuhammadMuhammad,146.66,220448008.0,ShofiyyurrohmanShofiyyurrohman,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,MuhammadMuhammad,133.34,220448006.0,Bintang GunawanBintang Gunawan,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,RafliRafli,133.34,220448164.0,SidqimudinSidqimudin,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,SyauqiSyauqi,133.34,220448416.0,RabbaniRabbani,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,179.26,NaN,Overall averageOverall average,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
df_excel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 26 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Last name      46 non-null     object
 1   First name     45 non-null     object
 2   Username       45 non-null     float64
 3   ID number      45 non-null     float64
 4   Email address  45 non-null     object
 5   Mobile phone   0 non-null      float64
 6   State          45 non-null     object
 7   Started on     45 non-null     object
 8   Completed      45 non-null     object
 9   Time taken     45 non-null     object
 10  Grade/100.00   46 non-null     float64
 11  Q. 1 /6.67     46 non-null     float64
 12  Q. 2 /6.67     46 non-null     float64
 13  Q. 3 /6.67     46 non-null     float64
 14  Q. 4 /6.67     46 non-null     float64
 15  Q. 5 /6.67     46 non-null     object
 16  Q. 6 /6.67     46 non-null     object
 17  Q. 7 /6.67     46 non-null     float64
 18  Q. 8 /6.67     46 non-null     float64
 19  Q. 9 /6.67     46 non-null     float64
 20  Q. 10 /6.67    46 non-null     object
 21  Q. 11 /6.67    46 non-null     float64
 22  Q. 12 /6.67    46 non-null     float64
 23  Q. 13 /6.67    46 non-null     object
 24  Q. 14 /6.67    46 non-null     float64
 25  Q. 15 /6.67    46 non-null     float64
dtypes: float64(15), object(11)
memory usage: 9.5+ KB

In [36]:
print(df_mysql['nim'].head(5))
print(df_excel['ID number'].head(5))

0    0110221344
1    0110224003
2    0110224004
3    0110224009
4    0110224012
Name: nim, dtype: object
0    110224069.0
1    110224228.0
2    110224028.0
3    110224155.0
4    110224019.0
Name: ID number, dtype: float64

In [28]:
# ubah id number jadikan integer karena akan membuang angka decimal di akhir
df_excel['ID number'] = df_excel ['ID number'].fillna(0).astype(int).astype(str)
df_excel.head()

#tambahan "0" didepan ID number : pola dari nim
df_excel['ID number'] = "0" + df_excel['ID number']
df_excel.head()

,Last name,First name,Username,ID number,Email address,Mobile phone,State,Started on,Completed,Time taken,...,Q. 6 /6.67,Q. 7 /6.67,Q. 8 /6.67,Q. 9 /6.67,Q. 10 /6.67,Q. 11 /6.67,Q. 12 /6.67,Q. 13 /6.67,Q. 14 /6.67,Q. 15 /6.67
0,Farhan Apriliansyah,Muhamad,110224069.0,0110224069,0110224069@student.nurulfikri.ac.id,NaN,Finished,13 April 2026 8:17 AM,13 April 2026 8:22 AM,5 mins 54 secs,...,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67
1,Farrelia,Keyla,110224228.0,0110224228,0110224228@student.nurulfikri.ac.id,NaN,Finished,13 April 2026 8:20 AM,13 April 2026 8:29 AM,9 mins 32 secs,...,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67
2,Febriyanti,Intan,110224028.0,0110224028,0110224028@student.nurulfikri.ac.id,NaN,Finished,13 April 2026 8:20 AM,13 April 2026 8:30 AM,9 mins 29 secs,...,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67
3,Al Razzak,Rafa,110224155.0,0110224155,0110224155@student.nurulfikri.ac.id,NaN,Finished,13 April 2026 8:20 AM,13 April 2026 8:27 AM,7 mins 3 secs,...,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67
4,Zahrodiniah,Silvia,110224019.0,0110224019,0110224019@student.nurulfikri.ac.id,NaN,Finished,13 April 2026 8:20 AM,13 April 2026 8:30 AM,10 mins,...,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67

In [30]:
# Standarisasi type data. agar aman samakan tipe data nya dahulu, dari excel ID number dari mysql nim

df_excel = df_excel.copy()
df_mysql = df_mysql.copy()

df_excel['ID number'] = df_excel['ID number'].astype(str)
df_mysql['nim'] = df_mysql['nim'].astype(str)

In [32]:
# Integrasi (penggabungan data)

df_integrasi = pd.merge(
    df_mysql,df_excel,
    left_on='nim',
    right_on='ID number',
    how='inner'

)

df_integrasi.head()

,id,nim,nama,angkatan,prodi,kode_kelas,Last name,First name,Username,ID number,...,Q. 6 /6.67,Q. 7 /6.67,Q. 8 /6.67,Q. 9 /6.67,Q. 10 /6.67,Q. 11 /6.67,Q. 12 /6.67,Q. 13 /6.67,Q. 14 /6.67,Q. 15 /6.67
0,2,0110224003,MUHAMMAD BINTANG GUNAWAN,2024,TI,DM20252-P,Bintang Gunawan,Muhammad,110224003.0,0110224003,...,0.00,6.67,0.00,6.67,6.67,0.00,6.67,6.67,6.67,0.00
1,3,0110224004,MUHAMMAD SHOFIYYURROHMAN,2024,TI,DM20252-P,Shofiyyurrohman,Muhammad,110224004.0,0110224004,...,-,6.67,6.67,6.67,-,6.67,6.67,-,6.67,6.67
2,4,0110224009,ZAINAB AZNUR,2024,TI,DM20252-P,Aznur,Zainab,110224009.0,0110224009,...,6.67,6.67,0.00,0.00,6.67,6.67,6.67,6.67,0.00,0.00
3,5,0110224012,ARYA NURYAWAN,2024,TI,DM20252-P,Nuryawan,Arya,110224012.0,0110224012,...,6.67,6.67,6.67,6.67,6.67,6.67,0.00,6.67,0.00,6.67
4,6,0110224014,AAN ADRIYANA,2024,TI,DM20252-P,Adriyana,Aan,110224014.0,0110224014,...,6.67,6.67,6.67,6.67,0.00,6.67,6.67,6.67,6.67,6.67

In [34]:
# buat dataframe agar lebih rapih
df_integrasi = df_integrasi[['id', 'nim', 'nama','Grade/100.00']]

df_integrasi.head()

   id         nim                      nama  Grade/100.00
0   2  0110224003  MUHAMMAD BINTANG GUNAWAN         66.67
1   3  0110224004  MUHAMMAD SHOFIYYURROHMAN         73.33
2   4  0110224009              ZAINAB AZNUR         73.33
3   5  0110224012             ARYA NURYAWAN         80.00
4   6  0110224014              AAN ADRIYANA         93.33

In [36]:
# rename Grade/100.00 menjadi nilai

df_integrasi.rename(columns={'Grade/100.00': 'nilai'}, inplace=True)

df_integrasi.head()

   id         nim                      nama  nilai
0   2  0110224003  MUHAMMAD BINTANG GUNAWAN  66.67
1   3  0110224004  MUHAMMAD SHOFIYYURROHMAN  73.33
2   4  0110224009              ZAINAB AZNUR  73.33
3   5  0110224012             ARYA NURYAWAN  80.00
4   6  0110224014              AAN ADRIYANA  93.33

In [38]:
df_integrasi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      19 non-null     int64
 1   nim     19 non-null     object
 2   nama    19 non-null     object
 3   nilai   19 non-null     float64
dtypes: float64(1), int64(1), object(2)
memory usage: 740.0+ bytes

In [42]:
set(df_mysql['nim']) - set(df_excel['ID number'])

{'0110221344',
 '0110224027',
 '0110224032',
 '0110224038',
 '0110224045',
 '0110224047',
 '0110224049',
 '0110224056',
 '0110224058',
 '0110224065',
 '0110224078',
 '0110224083',
 '0110224090',
 '0110224098',
 '0110224100',
 '0110224107',
 '0110224114',
 '0110224117',
 '0110224120',
 '0110224125',
 '0110224128',
 '0110224132',
 '0110224135',
 '0110224141',
 '0110224144',
 '0110224146',
 '0110224147',
 '0110224151',
 '0110224156',
 '0110224160',
 '0110224161',
 '0110224164',
 '0110224167',
 '0110224170',
 '0110224172',
 '0110224176',
 '0110224179',
 '0110224185',
 '0110224188',
 '0110224189',
 '0110224190',
 '0110224191',
 '0110224192',
 '0110224194',
 '0110224196',
 '0110224197',
 '0110224198',
 '0110224200',
 '0110224202',
 '0110224203',
 '0110224205',
 '0110224207',
 '0110224209',
 '0110224210',
 '0110224212',
 '0110224215',
 '0110224216',
 '0110224217',
 '0110224218',
 '0110224219',
 '0110224220',
 '0110224221',
 '0110224222',
 '0110224223',
 '0110224224',
 '0110224225',
 '0110224226',
 '0110224227',
 '0110224229',
 '0110224230',
 '0110224231',
 '0110224232',
 '0110224233',
 '0110224235',
 '0110224236',
 '0110224237',
 '0110224238'}

In [44]:
set(df_excel['ID number']) - set(df_mysql['nim'])

{'00',
 '0110224028',
 '0110224031',
 '0110224033',
 '0110224043',
 '0110224052',
 '0110224053',
 '0110224057',
 '0110224060',
 '0110224066',
 '0110224069',
 '0110224080',
 '0110224081',
 '0110224082',
 '0110224084',
 '0110224089',
 '0110224095',
 '0110224096',
 '0110224102',
 '0110224111',
 '0110224112',
 '0110224113',
 '0110224116',
 '0110224131',
 '0110224155',
 '0110224171',
 '0110224240'}